'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BakedGood

    '''<summary>
    '''lstBakedGoods control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstBakedGoods As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''txtBG_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBG_ID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBGName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBGName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBGPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBGPrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkBG_Discontinued control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkBG_Discontinued As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnBG_AddItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBG_AddItem As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBG_UpdateItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBG_UpdateItem As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBG_SaveAsNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBG_SaveAsNew As Global.System.Web.UI.WebControls.Button
End Class
