
'* Screen Name: BakedGood. 
'* Designer: Ken Baker 4/12/2013. 
'* Purpose:  Allow the Owner to create, view, alter, or discontinue baked product offerings for sale.
'*
'* Create a new Baked Good offering (two methods): 
'*     1) "Save As New" button: Click 
'*          Allows the user to select an existing item, make changes, and save it as a new bakedGood object (generates a new BakedGoodID).
'*     2)  Click "Add Item" button: Click.  
'*          The owner may enter the desired information into the appropriate fields and click "Add Item".  
'*          The new BakedGood object will appear in the "Available Baked Goods" listbox, and in the customer's baked goods order menu.
'*
'* "Update Item" button: Click
'* Updates the baked good object shown in the listbox to reflect current textbox values.
'* 
'* "Close" button: Click
'* Redirects Owner to Default.aspx
'*
'* "Available Baked Goods" listbox:
'* The owner may select an object from the list.  The values are displayed in the associated textbox controls.
'*
'* "Discontinued Item" checkbox(selected = true): 
'* If selected , the the item will no longer be produced.  The Item will also be removed from the customers baked goods order menu.
'* If selected, all textbox controls are disabled.
'* If selected, The product information can still be used as a template for a new product by clicking the "Save As New" button.
'*
'* ProductID:
'* This textbox is always disabled.  The ProductID is autogenerated by the database when the new record is inserted.



Public Class BakedGood
    Inherits System.Web.UI.Page

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

        txtBG_ID.Enabled = False

    End Sub

    Protected Sub btnBG_Close_Click(sender As Object, e As EventArgs) Handles btnBG_Close.Click
        Response.Redirect("Default.aspx")
    End Sub
End Class