'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BakedGoodMenu

    '''<summary>
    '''lstMenu_Items control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstMenu_Items As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''txtMenu_ProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMenu_ProductID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMenu_ItemName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMenu_ItemName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMenu_Price control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMenu_Price As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkMenu_ItemSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMenu_ItemSelect As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtMenu_Quantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMenu_Quantity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnMenu_AddItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMenu_AddItem As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnMenu_Cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMenu_Cancel As Global.System.Web.UI.WebControls.Button
End Class
