<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/Site.Master" CodeBehind="BakedGood.aspx.vb"
Inherits="WBE_WebApplication.BakedGood" %>

<asp:Content ID="Content1" runat="server" contentplaceholderid="MainContent">
    <table class="style1">
        <tr>
            <td class="style50" colspan="3">
                <strong>Screen Name:</strong> BakedGood.
                <br />
                <strong>Designer:</strong> Ken Baker 4/12/2013.
                <br />
                <strong>Purpose:</strong>&nbsp; Allow the Owner to create, view, alter, or 
                discontinue baked product offerings for sale.<br />
                <br />
                <strong>Create a new Baked Good offering (two methods): </strong>
                <br />
&nbsp;&nbsp;&nbsp;&nbsp; <span class="style23">1) &quot;Save As New&quot; button: Click<strong> </strong>
                </span>
                <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Allows the user to select an existing 
                item, make changes, and save it as a new bakedGood object (generates a new 
                BakedGoodID).<br />
&nbsp;&nbsp;&nbsp;&nbsp; <span class="style23">2)&nbsp; Click &quot;Add Item&quot; button: Click.</span>&nbsp;
                <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The owner may enter the desired 
                information into the appropriate fields and click &quot;Add Item&quot;.&nbsp;
                <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The new BakedGood object will appear in 
                the &quot;Available Baked Goods&quot; listbox, and in the customer&#39;s baked goods order 
                menu.<br />
&nbsp;<strong><br />
                &quot;Update Item&quot; button: Click</strong><br />
                Updates the baked good object shown in the listbox to reflect current textbox values.<br />
                <br />
                <strong>&quot;Close&quot; button: Click<br />
                </strong>Redirects Owner to Default.aspx<br />
                <br />
                <strong>&quot;Available Baked Goods&quot; listbox:<br />
                </strong>The owner may select an object from the list.&nbsp; The values are 
                displayed in the associated textbox controls.<br />
                <br />
                <strong>&quot;Discontinued Item&quot; checkbox(selected = true): </strong>
                <br />
                If selected , the the item will no longer be produced.&nbsp; The Item will also 
                be removed from the customers baked goods order menu.<br />
                If selected, all textbox controls are disabled.<br />
                If selected, The product information can still be used as a template for a new 
                product by clicking the &quot;Save As New&quot; button.<br />
                <br />
                <strong>ProductID:</strong><br />
                This textbox is always disabled.&nbsp; The ProductID is autogenerated by the 
                database when the new record is inserted.<br />
            </td>
        </tr>
        <tr>
            <td class="style2" rowspan="3">
            </td>
            <td class="style6">
                Product Information</td>
            <td class="style24">
                </td>
        </tr>
        <tr>
            <td class="style11">
                Available Baked Goods</td>
            <td class="style25" valign="middle">
                &nbsp;&nbsp;&nbsp;
            </td>
        </tr>
        <tr>
            <td class="style9">
                <asp:ListBox ID="lstBakedGoods" runat="server" Height="132px" Width="259px">
                </asp:ListBox>
            </td>
            <td class="style20">
                <table class="style46">
                    <tr>
                        <td class="style44">
                            Product ID&nbsp;&nbsp;&nbsp;</td>
                        <td class="style45">
                <asp:TextBox ID="txtBG_ID" runat="server"></asp:TextBox>
                        </td>
                    </tr>
                    <tr>
                        <td class="style15">
                            Name 
                        </td>
                        <td>
                            <asp:TextBox ID="txtBGName" runat="server"></asp:TextBox>
                        </td>
                    </tr>
                    <tr>
                        <td class="style15">
                            Price
                        </td>
                        <td>
                            <asp:TextBox ID="txtBGPrice" runat="server"></asp:TextBox>
                        </td>
                    </tr>
                    <tr>
                        <td class="style15">
                            Discontinued</td>
                        <td>
                            <asp:CheckBox ID="chkBG_Discontinued" runat="server" />
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        </table>
    <table class="style1">
        <tr>
            <td class="style47">
                &nbsp;</td>
            <td class="style48">
                <asp:Button ID="btnBG_AddItem" runat="server" Text="Add Item" />
                        </td>
            <td class="style49">
                <asp:Button ID="btnBG_UpdateItem" runat="server" Text="Update Item" 
                    Width="119px" />
                        </td>
            <td class="style51">
                <asp:Button ID="btnBG_SaveAsNew" runat="server" Text="Save As New" />
            </td>
            <td>
                <asp:Button ID="btnBG_Close" runat="server" Text="Close" Width="93px" />
            </td>
        </tr>
    </table>
    <br />
    </asp:Content>
<asp:Content ID="Content2" runat="server" contentplaceholderid="HeadContent">
    <style type="text/css">
        .style1
        {
            width: 100%;
        }
        .style2
        {
            font-family: Verdana;
            font-size: x-large;
            width: 34px;
            }
        .style6
        {
            font-family: Verdana;
            font-size: x-large;
            width: 242px;
            height: 33px;
            text-align: left;
        }
        .style9
        {
            width: 242px;
            height: 149px;
        }
        .style11
        {
            font-family: Verdana;
            font-size: small;
            width: 242px;
            height: 6px;
        }
        .style15
        {
            width: 88px;
        }
        .style20
        {
            width: 506px;
            height: 149px;
        }
        .style24
        {
            width: 506px;
            height: 33px;
        }
        .style25
        {
            width: 506px;
            height: 6px;
        }
        .style44
        {
            width: 88px;
            height: 20px;
        }
        .style45
        {
            height: 20px;
        }
        .style46
        {
            width: 100%;
            height: 129px;
        }
        .style47
        {
            width: 36px;
        }
        .style48
        {
            width: 110px;
        }
        .style49
        {
            width: 162px;
            text-align: left;
        }
        .style50
        {
            font-family: Verdana;
            font-size: small;
            height: 33px;
        }
        .style23
        {
            text-decoration: underline;
        }
        .style51
        {
            width: 155px;
        }
    </style>
</asp:Content>





