'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Orders

    '''<summary>
    '''lstCustomerOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstCustomerOrders As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''txtO_OrderID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtO_OrderID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtO_OrderDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtO_OrderDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkO_OrderShipped control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkO_OrderShipped As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtO_TotalCharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtO_TotalCharge As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnRecalcTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRecalcTotal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnO_DeleteOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnO_DeleteOrder As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lstOrderItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstOrderItems As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''txtOI_ItemID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOI_ItemID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOI_ItemName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOI_ItemName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOI_QuantityOrdered control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOI_QuantityOrdered As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOI_UnitPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOI_UnitPrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOI_ExtendPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOI_ExtendPrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnOI_UpdateItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOI_UpdateItem As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnIO_DeleteItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnIO_DeleteItem As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnOI_AddItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOI_AddItem As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnOI_SaveAsNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOI_SaveAsNew As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCreateInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateInvoice As Global.System.Web.UI.WebControls.Button
End Class
