'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Orders

    '''<summary>
    '''lstCustomerOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstCustomerOrders As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''txtOrderID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrderID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtO_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtO_Date As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkO_TransactionComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkO_TransactionComplete As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtO_TotalCharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtO_TotalCharge As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lstOrderItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstOrderItems As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''txtOI_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOI_ID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOI_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOI_Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOI_Quantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOI_Quantity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOI_UnitPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOI_UnitPrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOI_ExtendPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOI_ExtendPrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnAddOI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddOI As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnUpdateOI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateOI As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCreateInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateInvoice As Global.System.Web.UI.WebControls.Button
End Class
